### PR TITLE
Converting project to use browserify and CommonJS for the structure/build

### PR DESCRIPTION
**Pull request by RangerMauve**
A bunch of folders have been converted to use `require` to get dependencies, and `module.exports` to export resources.

Building can be done by running `npm run build` and that should output to `build/glam.js`. Make sure to do an `npm install` before starting development for the first time, to install the dev dependencies. Currently the actual dependencies have not been added, and it might be a good idea to do that after everything has been converted to using CommonJS.

The build works by looking in `src/index.js` and then following `require()` calls to other files.

The final built file creates a global variable `glam` which is equal to the `module.exports` within `src/index.js`

Converted Folders:
- animations
- behaviours
- cameras
- controllers
- core
- events
- graphics (It seems that there's a missing glam.Composer dependency here)

### CODE REVIEW

**Comment by tparisi** [comment]
Hey it looks like you made the commits against master instead of the branch? Unless I am misreading this

**Comment by RangerMauve** [comment]
Oh, it's master from my fork, but it'd be merged into browserify-build on in your version. Probably should have made a branch in my fork, too. :P

**Comment by tparisi** [comment]
Cool - I guess this is a Github dumbass question then because I tried to figure out what branch it was forked from and couldn't. Any tips on how to do that?

**Comment by RangerMauve** [comment]
Oh, I forked from master originally. Then I merged with your master in 6436bce, then I merged with your browserify-build branch in 7ce192c.

**Comment by tparisi** [comment]
OK I'm going to assume that your PR won't clobber the current build system in master? I want to be sure about this before I switch everybody over (but especially myself ;->)

**Comment by tparisi** [comment]
Yeah that worked - it's all in the branch. OK I'll test this out over the next day or so. In and out for the rest of the weekend. Thanks again!

**Comment by RangerMauve** [comment]
No problem. Also, it doesn't really build anything usable for now. And probably won't until its all converted. :P

**Comment by tparisi** [comment]
@RangerMauve Hey finally picking this up a year later :-) I fixed a trailing comma in the JSON (checked in) but the build gives me the errors below. Any clues?

$ npm run build

> glam@0.0.0 build /Users/Tony/dev/Github/glam
> watchify ./ -o -s glam build/glam.js

You MUST specify an outfile with -o.

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.2.2
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! glam@0.0.0 build: `watchify ./ -o -s glam build/glam.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the glam@0.0.0 build script 'watchify ./ -o -s glam build/glam.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the glam package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     watchify ./ -o -s glam build/glam.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls glam
npm ERR! There is likely additional logging output above.

**Comment by RangerMauve** [comment]
My bad! I messed up setting up the auto-rebuild script. [this line](https://github.com/tparisi/glam/blob/browserify-build/package.json#L13) should be changed to

``` bash
"watch": "watchify ./ -s glam -o  build/glam.js",
```

**Pull request merged**
